# Generated manually for the initial Control Center domain schema.

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AgentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=32)),
                ('queue_depth', models.PositiveIntegerField(default=0)),
                ('tool_success_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('token_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active_incidents', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('snapshot_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={'ordering': ['-snapshot_at']},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=120)),
                ('target_type', models.CharField(max_length=80)),
                ('target_identifier', models.CharField(max_length=120)),
                ('result', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('denied', 'Denied')], max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={'ordering': ['-occurred_at']},
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('environment_type', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('test', 'Test'), ('development', 'Development')], default='production', max_length=32)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('is_customer_facing', models.BooleanField(default=True)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('team_type', models.CharField(choices=[('platform', 'Platform'), ('application', 'Application'), ('sre', 'SRE'), ('security', 'Security')], default='sre', max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('slack_channel', models.CharField(blank=True, max_length=80)),
                ('escalation_policy', models.CharField(blank=True, max_length=255)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('tier0', 'Tier 0'), ('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3')], default='tier2', max_length=16)),
                ('lifecycle', models.CharField(choices=[('experiment', 'Experiment'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='active', max_length=16)),
                ('repository_url', models.URLField(blank=True)),
                ('runbook_url', models.URLField(blank=True)),
                ('owning_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='controlcenter.team')),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Runbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('domain', models.CharField(choices=[('observability', 'Observability'), ('incident', 'Incident'), ('automation', 'Automation'), ('knowledge', 'Knowledge'), ('chatops', 'ChatOps'), ('governance', 'Governance')], max_length=32)),
                ('description', models.TextField()),
                ('steps', models.JSONField(blank=True, default=list)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('requires_approval', models.BooleanField(default=True)),
                ('linked_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runbooks', to='controlcenter.service')),
            ],
            options={'ordering': ['domain', 'name']},
        ),
        migrations.CreateModel(
            name='ServiceEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.CharField(blank=True, max_length=120)),
                ('cluster', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_environments', to='controlcenter.environment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_environments', to='controlcenter.service')),
            ],
            options={'ordering': ['service__name', 'environment__name']},
        ),
        migrations.AddField(
            model_name='service',
            name='environments',
            field=models.ManyToManyField(related_name='services', through='controlcenter.ServiceEnvironment', to='controlcenter.environment'),
        ),
        migrations.CreateModel(
            name='ServiceDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependency_type', models.CharField(choices=[('synchronous', 'Synchronous'), ('asynchronous', 'Asynchronous'), ('data', 'Data'), ('third_party', 'Third Party')], max_length=32)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('slo_impact', models.CharField(blank=True, max_length=255)),
                ('downstream_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_dependencies', to='controlcenter.service')),
                ('upstream_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_dependencies', to='controlcenter.service')),
            ],
            options={'ordering': ['upstream_service__name', 'downstream_service__name']},
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('source', models.CharField(choices=[('prometheus', 'Prometheus'), ('loki', 'Loki'), ('tempo', 'Tempo'), ('cloud_monitor', 'Cloud Monitor')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('expression', models.TextField()),
                ('threshold', models.CharField(blank=True, max_length=120)),
                ('for_duration', models.DurationField(blank=True, null=True)),
                ('summary_template', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='controlcenter.environment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='controlcenter.service')),
            ],
            options={'ordering': ['service__name', 'name']},
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('severity', models.CharField(choices=[('sev0', 'SEV0'), ('sev1', 'SEV1'), ('sev2', 'SEV2'), ('sev3', 'SEV3')], max_length=8)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('triaged', 'Triaged'), ('mitigating', 'Mitigating'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='detected', max_length=16)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('root_cause_summary', models.TextField(blank=True)),
                ('impact_summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('alert_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='controlcenter.alertrule')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='controlcenter.environment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='controlcenter.service')),
            ],
            options={'ordering': ['-detected_at']},
        ),
        migrations.CreateModel(
            name='IncidentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('rule_engine', 'Rule Engine'), ('statistical', 'Statistical'), ('llm', 'LLM'), ('hybrid', 'Hybrid')], default='hybrid', max_length=32)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('horizon_minutes', models.PositiveIntegerField()),
                ('probable_cause', models.CharField(max_length=255)),
                ('recommended_action', models.TextField()),
                ('supporting_signals', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_predictions', to='controlcenter.environment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_predictions', to='controlcenter.service')),
            ],
            options={'ordering': ['-generated_at']},
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('document_type', models.CharField(choices=[('sop', 'SOP'), ('postmortem', 'Postmortem'), ('architecture', 'Architecture'), ('cmdb', 'CMDB'), ('faq', 'FAQ')], max_length=32)),
                ('source_uri', models.URLField(blank=True)),
                ('summary', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('freshness_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to='controlcenter.incident')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to='controlcenter.service')),
            ],
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executor_type', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent'), ('workflow', 'Workflow')], default='agent', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=16)),
                ('approval_reference', models.CharField(blank=True, max_length=120)),
                ('dry_run', models.BooleanField(default=False)),
                ('execution_log', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_executions', to='controlcenter.environment')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_executions', to='controlcenter.incident')),
                ('runbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='controlcenter.runbook')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_executions', to='controlcenter.service')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('persona', models.CharField(choices=[('operator', 'Operator'), ('incident_commander', 'Incident Commander'), ('executive', 'Executive'), ('agent', 'Agent')], default='operator', max_length=32)),
                ('user_identifier', models.CharField(max_length=120)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='controlcenter.incident')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='controlcenter.service')),
            ],
            options={'ordering': ['-last_message_at']},
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], max_length=16)),
                ('message_type', models.CharField(choices=[('query', 'Query'), ('answer', 'Answer'), ('action', 'Action'), ('summary', 'Summary')], default='query', max_length=16)),
                ('content', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list)),
                ('token_usage', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='controlcenter.chatsession')),
            ],
            options={'ordering': ['created_at']},
        ),
        migrations.AddConstraint(
            model_name='serviceenvironment',
            constraint=models.UniqueConstraint(fields=('service', 'environment'), name='unique_service_environment'),
        ),
        migrations.AddConstraint(
            model_name='servicedependency',
            constraint=models.UniqueConstraint(fields=('upstream_service', 'downstream_service'), name='unique_service_dependency'),
        ),
        migrations.AddConstraint(
            model_name='servicedependency',
            constraint=models.CheckConstraint(condition=~models.Q(upstream_service=models.F('downstream_service')), name='prevent_self_service_dependency'),
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.UniqueConstraint(fields=('service', 'environment', 'name'), name='unique_alert_rule_scope'),
        ),
    ]
